# Generated by Django 5.0.6 on 2024-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("comment", "Comment"),
                    ("registration", "Registration"),
                    ("follow", "Follow"),
                    ("unfollow", "Unfollow"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.CharField(max_length=100),
        ),
    ]
