version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: salmanyagaka
      RABBITMQ_DEFAULT_PASS: salma
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env

  web:
    image: limsapi/social_media:latest
    command: ["sh", "-c", "until python manage.py makemigrations && python manage.py migrate; do echo 'Waiting for db...'; sleep 5; done && gunicorn --bind 0.0.0.0:8000 social_media_project.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    command: ["sh", "-c", "until python manage.py makemigrations && python manage.py migrate; do echo 'Waiting for db...'; sleep 5; done && celery -A social_media_project worker --loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

  celery-beat:
    build: .
    command: ["sh", "-c", "until python manage.py makemigrations && python manage.py migrate; do echo 'Waiting for db...'; sleep 5; done && celery -A social_media_project beat --loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

  test:
    build: .
    command: ["sh", "-c", "until python manage.py makemigrations && python manage.py migrate; do echo 'Waiting for db...'; sleep 5; done && pytest --cov=social_media_project/apps --cov-report=term-missing --cov-report=html"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

volumes:
  postgres_data:
