version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 social_media_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: social_media_project
      POSTGRES_USER: social_media_project
      POSTGRES_PASSWORD: social_media_project
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
