version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social_media_project
      POSTGRES_USER: salmanyagaka
      POSTGRES_PASSWORD: 'salma'

  redis:
    image: redis:6

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: salmanyagaka
      RABBITMQ_DEFAULT_PASS: salma
    ports:
      - "15672:15672"
      - "5672:5672"

  web:
    build:
      context:  .
    #image: limsapi/social_media:latest
    command: ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 social_media_project.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq

  celery:
    build: .
    command: ["sh", "-c", "/wait-for-it.sh rabbitmq:5672 -- celery -A social_media_project worker --loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build: .
    command: ["sh", "-c", "/wait-for-it.sh rabbitmq:5672 -- celery -A social_media_project beat --loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

volumes:
  postgres_data:
