# Generated by Django 5.0.6 on 2024-06-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_service", "0003_post_user_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
