# Generated by Django 5.0.6 on 2024-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_service", "0004_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(null=True, unique=True),
        ),
    ]
