version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use the appropriate base image
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      # Setup Docker environment
      - setup_remote_docker:
          version: 20.10.7

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker-compose  up --build

      # Run tests
      - run:
          name: Run tests in image
          command: docker-compose run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
