version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
        environment:
          POSTGRES_DB: social_media_project
          POSTGRES_USER: salmanyagaka
          POSTGRES_PASSWORD: 'salma'
          RABBITMQ_DEFAULT_USER: salmanyagaka
          RABBITMQ_DEFAULT_PASS: salma

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start services
          command: sudo docker-compose up -d
      - run:
          name: Run tests
          command: sudo docker-compose run test
      - run:
          name: Tear down services
          command: sudo docker-compose down -v

workflows:
  sample:
    jobs:
      - build-and-test
