# Generated by Django 5.0.6 on 2024-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
