# Generated by Django 5.0.6 on 2024-06-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
