# Generated by Django 5.0.6 on 2024-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_service", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
