name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - setup_remote_docker:
          version: 20.10.7

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker-compose  up --build

      # Run tests
      - run:
          name: Run tests in image
          command: docker-compose run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 5dcfad2a-05bd-4c34-8096-f5a1c7292ffd
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella