name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      # - name: Setup Docker
      #   uses: docker/setup-buildx-action@v2

      # # Build Docker image
      # - name: Build Docker image
      #   run: docker-compose up --build -d

      # # Run tests in image
      # - name: Run tests in image
      #   run: docker-compose run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
