name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - fix-deployment-issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: limsapi/social_media:latest

      - name: Deploy to EC2
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        run: |
          cat > ec2_key.pem << 'EOF'
          ${SECRETS.EC2_KEY}
          EOF
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'SSH_EOF'
            set -e
            cd /opt/twiga/social_media || mkdir -p /opt/twiga/social_media && cd /opt/twiga/social_media
            git pull origin main
            
            # Ensure the .env file is created
            echo "Creating .env file with secrets..."
            echo "SECRET_KEY=${SECRET_KEY}" > .env
            echo "DATABASE_URL=${DATABASE_URL}" >> .env
            echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> .env
            echo "DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}" >> .env
            echo "DOMAIN_NAME=${DOMAIN_NAME}" >> .env
            cat .env
            
            # Pull the latest Docker images
            docker-compose pull
            
            # Remove any existing containers
            docker-compose down
            
            # Start Docker containers without rebuilding every time
            docker-compose up -d --build
          SSH_EOF
          rm ec2_key.pem
