name: Build and Push Docker Image

on:
  push:
    branches:
      - fix-deployment-issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest

      - name: Deploy
        run: |
          echo "Starting Docker Compose with environment variables..."
          echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" > .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          # echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          # echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> .env
          # echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          # echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          cat .env
          docker-compose up -d
    